import { StyleSheet } from 'react-native';
import { colors, fonts } from './theme';
export const styles = StyleSheet.create({
  app: { flex: 1, backgroundColor: colors.paper }, loading: { flex: 1, alignItems: 'center', justifyContent: 'center', backgroundColor: colors.paper, gap: 20, padding: 32 },
  header: { borderBottomWidth: 1, borderColor: colors.line, backgroundColor: colors.paper }, headerInner: { width: '100%', maxWidth: 1160, alignSelf: 'center', paddingHorizontal: 24, paddingVertical: 18, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', gap: 16 },
  brand: { flexDirection: 'row', alignItems: 'center', gap: 10, minHeight: 44 }, brandMark: { width: 31, height: 34, borderRadius: 9, backgroundColor: colors.accent, alignItems: 'center', justifyContent: 'center', transform: [{ rotate: '-8deg' }] }, wordmark: { fontFamily: fonts.display, color: colors.ink, fontSize: 27, letterSpacing: -.8 },
  row: { flexDirection: 'row', alignItems: 'center', gap: 10 }, scroll: { flexGrow: 1, paddingBottom: 56 }, content: { alignSelf: 'center', width: '100%', maxWidth: 1120, paddingHorizontal: 24, paddingTop: 28 },
  intro: { gap: 28, paddingTop: 12, paddingBottom: 44 }, introWide: { flexDirection: 'row', gap: 64, paddingTop: 32, paddingBottom: 48 },
  heroTitle: { fontFamily: fonts.display, color: colors.ink, fontSize: 54, lineHeight: 58, letterSpacing: -1.5 }, pageTitle: { fontFamily: fonts.display, color: colors.ink, fontSize: 39, lineHeight: 45, letterSpacing: -.8 },
  sectionBar: { minHeight: 62, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', gap: 16, borderBottomWidth: 1, borderColor: colors.line, marginBottom: 28 },
  tabs: { flexDirection: 'row', alignItems: 'stretch', gap: 22 }, tab: { minHeight: 62, justifyContent: 'center', borderBottomWidth: 2, borderColor: 'transparent' }, tabActive: { borderColor: colors.accent }, tabText: { fontFamily: fonts.medium, fontSize: 14, color: colors.muted },
  sampleFeature: { gap: 0, borderRadius: 16, overflow: 'hidden', backgroundColor: colors.surface }, sampleCopy: { padding: 28, gap: 16, justifyContent: 'center' }, sampleTitle: { fontFamily: fonts.display, color: colors.ink, fontSize: 36, lineHeight: 40, letterSpacing: -.5 }, sampleLabel: { fontFamily: fonts.body, fontSize: 11, color: colors.muted, lineHeight: 17, marginTop: 6 },
  grid: { gap: 24 }, projectCard: { overflow: 'hidden', backgroundColor: colors.surface, borderRadius: 14 }, cardBody: { padding: 22, gap: 12 }, cardTitle: { fontFamily: fonts.display, color: colors.ink, fontSize: 27, lineHeight: 32 }, actionText: { color: colors.accent, fontFamily: fonts.bold, fontSize: 14 },
  meta: { fontFamily: fonts.body, color: colors.muted, fontSize: 12, lineHeight: 18 }, bottomNote: { gap: 16, marginTop: 30, paddingTop: 24, borderTopWidth: 1, borderColor: colors.line, alignItems: 'flex-start', justifyContent: 'space-between' },
  draftBanner: { backgroundColor: colors.accentSoft, borderRadius: 12, padding: 20, flexDirection: 'row', gap: 12, alignItems: 'center', marginBottom: 24 }, smallTitle: { fontFamily: fonts.medium, color: colors.ink, fontSize: 16, lineHeight: 24 },
  empty: { padding: 42, alignItems: 'center', gap: 16 }, back: { alignSelf: 'flex-start', marginLeft: -12, marginBottom: 22 },
  editorLayout: { gap: 32, alignItems: 'stretch' }, form: { gap: 22 }, input: { fontFamily: fonts.body, color: colors.ink, fontSize: 16, lineHeight: 24, padding: 16, backgroundColor: colors.surface, borderWidth: 1, borderColor: colors.line, borderRadius: 10, minHeight: 56 },
  photoPlaceholder: { aspectRatio: 4 / 3, borderWidth: 1, borderStyle: 'dashed', borderColor: colors.muted, backgroundColor: colors.surface, borderRadius: 12, alignItems: 'center', justifyContent: 'center', gap: 14, padding: 22 }, cameraCircle: { width: 68, height: 68, borderRadius: 34, backgroundColor: colors.accentSoft, alignItems: 'center', justifyContent: 'center' },
  banner: { flexDirection: 'row', alignItems: 'center', gap: 8, borderRadius: 10, paddingLeft: 16, paddingRight: 4, marginBottom: 16 }, errorBanner: { backgroundColor: '#FAE8E4' }, noticeBanner: { backgroundColor: colors.mossSoft }, formError: { fontFamily: fonts.medium, fontSize: 13, lineHeight: 20, color: colors.error },
  pieceHeader: { gap: 16, marginBottom: 28 }, resumePanel: { backgroundColor: colors.surface, borderRadius: 14, padding: 28, gap: 18 }, numberMark: { borderWidth: 1, borderColor: colors.line, width: 42, height: 42, alignItems: 'center', justifyContent: 'center', borderRadius: 21 }, numberText: { color: colors.accent, fontFamily: fonts.medium, fontSize: 15 }, nextMove: { fontFamily: fonts.display, fontSize: 30, lineHeight: 37, color: colors.ink },
  detailNote: { backgroundColor: colors.paper, borderRadius: 9, padding: 16, gap: 9 }, historyHeader: { marginTop: 36, marginBottom: 16, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', gap: 12 }, sectionTitle: { fontFamily: fonts.display, fontSize: 24, lineHeight: 30, color: colors.ink }, timeline: { borderTopWidth: 1, borderColor: colors.line }, timelineRow: { flexDirection: 'row', alignItems: 'flex-start', gap: 18, paddingVertical: 22, borderBottomWidth: 1, borderColor: colors.line }, timelineDot: { marginTop: 6, width: 10, height: 10, borderRadius: 5, backgroundColor: colors.accent },
  modalBackdrop: { flex: 1, backgroundColor: colors.overlay, padding: 20 }, modalScroll: { flexGrow: 1, justifyContent: 'center', alignItems: 'center' }, purchaseSheet: { width: '100%', maxWidth: 460, borderRadius: 22, backgroundColor: colors.paper, padding: 26, gap: 17 }, purchaseTitle: { fontFamily: fonts.display, color: colors.ink, fontSize: 36, lineHeight: 40 }, upgradeArt: { flexDirection: 'row', gap: 4, alignItems: 'center', paddingTop: 6 }, features: { gap: 12, paddingVertical: 8 },
});
